server:
  port: 8082
  address: 0.0.0.0

hssp:
  db:
    host: ${HSSP_DB_HOST}
    pw: ${HSSP_DB_PASSWORD}
  redis:
    host: ${HSSP_REDIS_HOST}
    port: ${HSSP_REDIS_PORT}
  qq:
    username: ${HSSP_QQ_USERNAME}
    code: ${HSSP_QQ_CODE}





