server:
  port: 8082
  address: 0.0.0.0

spring:
  application:
    name: hssp-user
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://${hssp.db.host}:3306/step_counter_db
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: ${hssp.db.pw}
