server:
  port: 8081
  address: 0.0.0.0

spring:
  application:
    name: hssp-admin
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://${hssp.db.host}:3306/step_counter_db
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: ${hssp.db.pw}

mybatis-plus:
  type-enums-package: com.hssp.common.admin
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
