server:
  port: 8081
  address: localhost

spring:
  application:
    name: hssp-admin
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://${hssp.db.host}:3306/step_counter_db
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: ${hssp.db.pw}
