server:
  port: 8080
  address: 0.0.0.0
spring:
  application:
    name: hssp-gateway
  cloud:
    nacos:
      discovery:
        enabled: false # 禁用 Nacos 服务注册
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            exposedHeaders:
              - Authorization
              - Content-Disposition
            maxAge: 3600
      routes:
        # 管理后台微服务
        - id: hssp-admin-route
          uri: http://localhost:8081
          predicates:
            - Path=/admin/**

        # 用户与排行榜微服务
        - id: hssp-user-route
          uri: http://localhost:8082
          predicates:
            - Path=/user/**

        # 商城中心微服务 (包含商品、积分、订单)
        - id: hssp-mall-route
          uri: http://localhost:8083
          predicates:
            - Path=/mall/**
          filters:
            - StripPrefix=1 # 移除 /mall 前缀再转发，例如 /mall/goods/list -> /goods/list
