spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - com.baomidou.mybatisplus.autoconfigure.MybatisPlusAutoConfiguration
  profiles:
    active: dev
  application:
    name: hssp-mall
  datasource:
    url: jdbc:mysql://${hssp.db.host}:3306/step_counter_db
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: ${hssp.db.pw}

  redis:
    host: ${hssp.redis.host}
    port: ${hssp.redis.port:6379}
    password: ${hssp.redis.pw}
    database: 0
    lettuce:
      pool:
        max-active: 8 # 最大连接数
        max-wait: -1ms
        max-idle: 8
        min-idle: 0

server:
  port: 8083 # 商城服务独立端口

mybatis-plus:
  # 关闭自动扫描别名 → 彻底解决 LoginDto / RegisterDto 冲突
  type-aliases-package:
  # 关闭 MyBatis 检查
  check-config-location: false
